# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.email_opt_in_out_api import EmailOptInOutApi


class TestEmailOptInOutApi(unittest.TestCase):
    """EmailOptInOutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailOptInOutApi()

    def tearDown(self) -> None:
        pass

    def test_get_email_preferences_for_a_user(self) -> None:
        """Test case for get_email_preferences_for_a_user

        Get all email preferences for the authenticated user
        """
        pass

    def test_toggle_all_optional_email_preferences_for_the_user(self) -> None:
        """Test case for toggle_all_optional_email_preferences_for_the_user

        Toggle all optional email preferences for the authenticated user
        """
        pass

    def test_update_email_preference_for_a_category_by_slug(self) -> None:
        """Test case for update_email_preference_for_a_category_by_slug

        Update email preference opted_in status for a category slug
        """
        pass


if __name__ == '__main__':
    unittest.main()
