# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.invite_user_payload import InviteUserPayload

class TestInviteUserPayload(unittest.TestCase):
    """InviteUserPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteUserPayload:
        """Test InviteUserPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteUserPayload`
        """
        model = InviteUserPayload()
        if include_optional:
            return InviteUserPayload(
                email = 'g98JLe5iL60+aa+-Ctq9dcsc-2+790gAa7Xa5u50ArrlGpCQjkQVRmF@9w-v0dZfUofvKERjsmInY9G.UMH6kw8gsnXv2Z7jRPK542XP.q.WR8pb-ziKqEde8fXg9wdpfxR.n.k.G.EU4NCUavTrirUe4ba7JnjrgEdBCJE-ArE6U3CZ-Vnrj9RmauZ.J.mRsCjOv6MeuvKGSDRGKUIQ8yNXhf.VbZpGptfI46.5.z.6-kwy.icMEEkIauY.eNaDi5ackLH.3.z-zmvqRnM-dar09VaHCQz0Tl8.D.rml4PJXMbVMO8G0e5q9Z4WMWovY63Gk6ixTd5NxRU25mQYd6VBLRK.Q.6-FH2v5iUaMQ6iIJ-7auxDSR-lIIfhhw9bP3XhsKpT6YkX2ymMVYtu.vpmKomcxVsOGUxBEnBeWManfNDKlIkmrRWZVNfdnqpXxVctlspfiaiRtKRxTMOFnGptSZASFERyiXQnrPBfV012345'
            )
        else:
            return InviteUserPayload(
                email = 'g98JLe5iL60+aa+-Ctq9dcsc-2+790gAa7Xa5u50ArrlGpCQjkQVRmF@9w-v0dZfUofvKERjsmInY9G.UMH6kw8gsnXv2Z7jRPK542XP.q.WR8pb-ziKqEde8fXg9wdpfxR.n.k.G.EU4NCUavTrirUe4ba7JnjrgEdBCJE-ArE6U3CZ-Vnrj9RmauZ.J.mRsCjOv6MeuvKGSDRGKUIQ8yNXhf.VbZpGptfI46.5.z.6-kwy.icMEEkIauY.eNaDi5ackLH.3.z-zmvqRnM-dar09VaHCQz0Tl8.D.rml4PJXMbVMO8G0e5q9Z4WMWovY63Gk6ixTd5NxRU25mQYd6VBLRK.Q.6-FH2v5iUaMQ6iIJ-7auxDSR-lIIfhhw9bP3XhsKpT6YkX2ymMVYtu.vpmKomcxVsOGUxBEnBeWManfNDKlIkmrRWZVNfdnqpXxVctlspfiaiRtKRxTMOFnGptSZASFERyiXQnrPBfV012345',
        )
        """

    def testInviteUserPayload(self):
        """Test InviteUserPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
