# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_change_organization_for_token(self) -> None:
        """Test case for change_organization_for_token

        """
        pass

    def test_disable_mfa(self) -> None:
        """Test case for disable_mfa

        """
        pass

    def test_get_authenticated_user(self) -> None:
        """Test case for get_authenticated_user

        Retrieve Authenticated User Details
        """
        pass

    def test_get_user_mfa_status(self) -> None:
        """Test case for get_user_mfa_status

        Get MFA status for authenticated user
        """
        pass

    def test_get_user_organizations(self) -> None:
        """Test case for get_user_organizations

        Get User Organizations
        """
        pass


if __name__ == '__main__':
    unittest.main()
