# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.auto_topup_api import AutoTopupApi


class TestAutoTopupApi(unittest.TestCase):
    """AutoTopupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutoTopupApi()

    def tearDown(self) -> None:
        pass

    def test_create_auto_top_up(self) -> None:
        """Test case for create_auto_top_up

        Create an auto top up configuration and initiate Stripe setup
        """
        pass

    def test_disable_auto_top_up(self) -> None:
        """Test case for disable_auto_top_up

        Disable auto top up, preventing any future automatic charges
        """
        pass

    def test_get_auto_top_up(self) -> None:
        """Test case for get_auto_top_up

        Retrieve the current auto top up configuration and transaction history
        """
        pass

    def test_get_auto_top_up_status(self) -> None:
        """Test case for get_auto_top_up_status

        Get auto top-up status and configuration
        """
        pass

    def test_update_auto_top_up(self) -> None:
        """Test case for update_auto_top_up

        Update an existing active auto top up configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
