# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.consent_events_response import ConsentEventsResponse

class TestConsentEventsResponse(unittest.TestCase):
    """ConsentEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsentEventsResponse:
        """Test ConsentEventsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsentEventsResponse`
        """
        model = ConsentEventsResponse()
        if include_optional:
            return ConsentEventsResponse(
                consent = hyperstack.models.user_consent.UserConsent(
                    action = '', 
                    consent_method = '', 
                    consent_type = '', 
                    created_at = '', 
                    id = 56, 
                    ip_address = '', 
                    org_id = 56, 
                    updated_at = '', 
                    user_id = 56, ),
                events = [
                    hyperstack.models.user_consent_event.UserConsentEvent(
                        action = '', 
                        consent_id = 56, 
                        consent_method = '', 
                        created_at = '', 
                        id = 56, 
                        ip_address = '', 
                        user_id = 56, )
                    ]
            )
        else:
            return ConsentEventsResponse(
        )
        """

    def testConsentEventsResponse(self):
        """Test ConsentEventsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
