# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.user_consent_api import UserConsentApi


class TestUserConsentApi(unittest.TestCase):
    """UserConsentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserConsentApi()

    def tearDown(self) -> None:
        pass

    def test_add_a_new_consent_for_a_user(self) -> None:
        """Test case for add_a_new_consent_for_a_user

        Add a new User consent
        """
        pass

    def test_get_all_consent_templates(self) -> None:
        """Test case for get_all_consent_templates

        Get all consent templates
        """
        pass

    def test_get_all_consents_for_a_user(self) -> None:
        """Test case for get_all_consents_for_a_user

        Get Consents for a User
        """
        pass

    def test_get_consent_template_by_type(self) -> None:
        """Test case for get_consent_template_by_type

        Get consent template for a specific type
        """
        pass

    def test_update_a_consent_action_by_type(self) -> None:
        """Test case for update_a_consent_action_by_type

        Grant or revoke an existing consent
        """
        pass


if __name__ == '__main__':
    unittest.main()
