# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ..models.compatible_flavor import CompatibleFlavor
from typing import Optional, Set
from typing_extensions import Self

class FlavorRestrictions(BaseModel):
    """
    FlavorRestrictions
    """ # noqa: E501
    compatible_flavors: Optional[List[CompatibleFlavor]] = Field(default=None, description="List of compatible flavors with their link metadata")
    has_flavor_restrictions: Optional[StrictBool] = Field(default=None, description="Whether the image has any flavor restrictions")
    restriction_type: Optional[StrictStr] = Field(default=None, description="Either 'hard', 'soft', or null if no restrictions")
    __properties: ClassVar[List[str]] = ["compatible_flavors", "has_flavor_restrictions", "restriction_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FlavorRestrictions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in compatible_flavors (list)
        _items = []
        if self.compatible_flavors:
            for _item_compatible_flavors in self.compatible_flavors:
                if _item_compatible_flavors:
                    _items.append(_item_compatible_flavors.to_dict())
            _dict['compatible_flavors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FlavorRestrictions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compatible_flavors": [CompatibleFlavor.from_dict(_item) for _item in obj["compatible_flavors"]] if obj.get("compatible_flavors") is not None else None,
            "has_flavor_restrictions": obj.get("has_flavor_restrictions"),
            "restriction_type": obj.get("restriction_type")
        })
        return _obj


